name = "tvic-crm"
main = "src/worker.ts"
compatibility_date = "2026-01-01"

assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "tvic_crm"
database_id = "33921d31-c4d7-4293-aebb-8bfaa638d527"
